package com.mvnikitin.sprdata.services;

import com.mvnikitin.sprdata.entities.Product;
import org.springframework.data.domain.PageRequest;

import java.util.List;
import java.util.Optional;

public interface ProductService {
    List<Product> getAll();
    List<Product> getById(Long id);
    void save(Product product);
    void remove(Long id);
    long count();

    // Custom autogenerated by Spring Data JPA
    List<Product> findByPriceBetween(double priceMin, double priceMax);
    long countByPriceBetween(double priceMin, double priceMax);

    PageInfo findByPage(int pageNumber, int rowsPerPage);
    PageInfo findByPage(int pageNumber, int rowsPerPage, double priceMin, double priceMax);
}
